repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-compose-spec
      - id: check-github-workflows
      - id: check-gitlab-ci

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
        require_serial: true
        pass_filenames: false
        types_or: [python, pyi]

default_stages: [pre-commit, pre-push, manual]
default_install_hook_types: [pre-commit, pre-push]
