services:
  backend:
    image: registry.gitlab.com/digital-fracture/itelma-backend:latest
    env_file:
      - .env
    volumes:
      - ../resources:/app/resources
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      default:
        aliases:
          - ${POSTGRES_HOST}

volumes:
  postgres:
