services:
  backend:
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    volumes:
      - ../app:/app/app:ro
      - ../pyproject.toml:/app/pyproject.toml:ro
      - ../uv.lock:/app/uv.lock:ro
      - ${UV_CACHE_DIR}:${UV_CACHE_DIR}
    working_dir: /app
    command: uv run -m app.cli --reload
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
    ports:
      - 8000:8000
    restart: always
